---
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff # run ruff equivalent of isort on everything
        args: ["--select", "I", "--target-version", "py39", "--fix"]
      - id: ruff
        files: ^tests/ # only check tests right now.
        args:
          [
            "--config",
            'lint.ignore = ["F401"]',
            "--target-version",
            "py39",
            "--fix",
          ]
      - id: ruff-format
        files: ^tests/ # we won't reformat everything yet.
        args: ["--target-version", "py39"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --py2 --ignore-missing-imports --scripts-are-modules --strict
        require_serial: true
        language: python
        types_or: [pyi, python]
        additional_dependencies:
          - "mypy[python2]==0.961"
