repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: c895849acf81cb9f744e4cdd73518b083ae586f1 # frozen: v3.8.5
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: 7b04f660f4ee4f048d18fd341887cf28dfbedfe2 # frozen: v1.46.3
    hooks:
      - id: typos

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2700fd5671c633760d912769c041bfcde2b9a01b # frozen: v0.15.22
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
        files: ^tests/ # we won't reformat everything yet.

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --no-project --python 3.9 --with "mypy[python2]==0.961" mypy --py2 --ignore-missing-imports --scripts-are-modules --strict --cache-dir /dev/null slackroll tests
        require_serial: true
        language: system
        types_or: [pyi, python]
        pass_filenames: false
