---
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        files: ^tests/
        additional_dependencies:
          - "click==8.0.4"

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --profile black
        language: python
        types_or: [cython, pyi, python]
        additional_dependencies:
          - "isort==5.10.1"

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --py2 --ignore-missing-imports --scripts-are-modules --strict
        require_serial: true
        language: python
        types_or: [pyi, python]
        additional_dependencies:
          - "mypy[python2]==0.961"
