---
name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          docker run --rm -v "$(pwd)":/slackroll acidrain/python-poetry:2.7-1.1.15 bash -c 'cd /slackroll && poetry env use 2.7 && poetry install && poetry run pytest'
